/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstructorRouteImport } from './routes/_instructor'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as ReinitialisationRouteImport } from './routes/reinitialisation'
import { Route as AuthInviteRouteImport } from './routes/_auth/invite'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as InstructorCommunauteRouteImport } from './routes/_instructor.communaute'
import { Route as InstructorCorrectionsRouteImport } from './routes/_instructor.corrections'
import { Route as InstructorProfilRouteImport } from './routes/_instructor.profil'
import { Route as InstructorSessionsRouteImport } from './routes/_instructor.sessions'
import { Route as InstructorDashboardRouteImport } from './routes/instructor/dashboard'
import { Route as InstructorApprenantsIndexRouteImport } from './routes/_instructor.apprenants.index'
import { Route as InstructorApprenantsStudentIdRouteImport } from './routes/_instructor.apprenants.$studentId'
import { Route as InstructorFormationsIndexRouteImport } from './routes/_instructor.formations.index'
import { Route as InstructorFormationsTrainingIdIndexRouteImport } from './routes/_instructor.formations.$trainingId.index'
import { Route as InstructorFormationsTrainingIdContenuRouteImport } from './routes/_instructor.formations.$trainingId.contenu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/_instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialisationRoute = ReinitialisationRouteImport.update({
  id: '/reinitialisation',
  path: '/reinitialisation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/_auth/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCommunauteRoute = InstructorCommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorCorrectionsRoute = InstructorCorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorProfilRoute = InstructorProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorSessionsRoute = InstructorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/instructor/dashboard',
  path: '/instructor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorApprenantsIndexRoute =
  InstructorApprenantsIndexRouteImport.update({
    id: '/apprenants/',
    path: '/apprenants/',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorApprenantsStudentIdRoute =
  InstructorApprenantsStudentIdRouteImport.update({
    id: '/apprenants/$studentId',
    path: '/apprenants/$studentId',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorFormationsIndexRoute =
  InstructorFormationsIndexRouteImport.update({
    id: '/formations/',
    path: '/formations/',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorFormationsTrainingIdIndexRoute =
  InstructorFormationsTrainingIdIndexRouteImport.update({
    id: '/formations/$trainingId/',
    path: '/formations/$trainingId/',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorFormationsTrainingIdContenuRoute =
  InstructorFormationsTrainingIdContenuRouteImport.update({
    id: '/formations/$trainingId/contenu',
    path: '/formations/$trainingId/contenu',
    getParentRoute: () => InstructorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/invite': typeof AuthInviteRoute
  '/login': typeof AuthLoginRoute
  '/communaute': typeof InstructorCommunauteRoute
  '/corrections': typeof InstructorCorrectionsRoute
  '/profil': typeof InstructorProfilRoute
  '/sessions': typeof InstructorSessionsRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/apprenants/$studentId': typeof InstructorApprenantsStudentIdRoute
  '/apprenants/': typeof InstructorApprenantsIndexRoute
  '/formations/': typeof InstructorFormationsIndexRoute
  '/formations/$trainingId/contenu': typeof InstructorFormationsTrainingIdContenuRoute
  '/formations/$trainingId/': typeof InstructorFormationsTrainingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/invite': typeof AuthInviteRoute
  '/login': typeof AuthLoginRoute
  '/communaute': typeof InstructorCommunauteRoute
  '/corrections': typeof InstructorCorrectionsRoute
  '/profil': typeof InstructorProfilRoute
  '/sessions': typeof InstructorSessionsRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/apprenants/$studentId': typeof InstructorApprenantsStudentIdRoute
  '/apprenants': typeof InstructorApprenantsIndexRoute
  '/formations': typeof InstructorFormationsIndexRoute
  '/formations/$trainingId/contenu': typeof InstructorFormationsTrainingIdContenuRoute
  '/formations/$trainingId': typeof InstructorFormationsTrainingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_instructor': typeof InstructorRouteWithChildren
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/_auth/invite': typeof AuthInviteRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_instructor/communaute': typeof InstructorCommunauteRoute
  '/_instructor/corrections': typeof InstructorCorrectionsRoute
  '/_instructor/profil': typeof InstructorProfilRoute
  '/_instructor/sessions': typeof InstructorSessionsRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/_instructor/apprenants/$studentId': typeof InstructorApprenantsStudentIdRoute
  '/_instructor/apprenants/': typeof InstructorApprenantsIndexRoute
  '/_instructor/formations/': typeof InstructorFormationsIndexRoute
  '/_instructor/formations/$trainingId/contenu': typeof InstructorFormationsTrainingIdContenuRoute
  '/_instructor/formations/$trainingId/': typeof InstructorFormationsTrainingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/reinitialisation'
    | '/invite'
    | '/login'
    | '/communaute'
    | '/corrections'
    | '/profil'
    | '/sessions'
    | '/instructor/dashboard'
    | '/apprenants/$studentId'
    | '/apprenants/'
    | '/formations/'
    | '/formations/$trainingId/contenu'
    | '/formations/$trainingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/reinitialisation'
    | '/invite'
    | '/login'
    | '/communaute'
    | '/corrections'
    | '/profil'
    | '/sessions'
    | '/instructor/dashboard'
    | '/apprenants/$studentId'
    | '/apprenants'
    | '/formations'
    | '/formations/$trainingId/contenu'
    | '/formations/$trainingId'
  id:
    | '__root__'
    | '/'
    | '/_instructor'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/reinitialisation'
    | '/_auth/invite'
    | '/_auth/login'
    | '/_instructor/communaute'
    | '/_instructor/corrections'
    | '/_instructor/profil'
    | '/_instructor/sessions'
    | '/instructor/dashboard'
    | '/_instructor/apprenants/$studentId'
    | '/_instructor/apprenants/'
    | '/_instructor/formations/'
    | '/_instructor/formations/$trainingId/contenu'
    | '/_instructor/formations/$trainingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstructorRoute: typeof InstructorRouteWithChildren
  InscriptionRoute: typeof InscriptionRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  ReinitialisationRoute: typeof ReinitialisationRoute
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_instructor': {
      id: '/_instructor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialisation': {
      id: '/reinitialisation'
      path: '/reinitialisation'
      fullPath: '/reinitialisation'
      preLoaderRoute: typeof ReinitialisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/invite': {
      id: '/_auth/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_instructor/communaute': {
      id: '/_instructor/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof InstructorCommunauteRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/corrections': {
      id: '/_instructor/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof InstructorCorrectionsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/profil': {
      id: '/_instructor/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof InstructorProfilRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/sessions': {
      id: '/_instructor/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof InstructorSessionsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/instructor/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_instructor/apprenants/': {
      id: '/_instructor/apprenants/'
      path: '/apprenants'
      fullPath: '/apprenants/'
      preLoaderRoute: typeof InstructorApprenantsIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/apprenants/$studentId': {
      id: '/_instructor/apprenants/$studentId'
      path: '/apprenants/$studentId'
      fullPath: '/apprenants/$studentId'
      preLoaderRoute: typeof InstructorApprenantsStudentIdRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/formations/': {
      id: '/_instructor/formations/'
      path: '/formations'
      fullPath: '/formations/'
      preLoaderRoute: typeof InstructorFormationsIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/formations/$trainingId/': {
      id: '/_instructor/formations/$trainingId/'
      path: '/formations/$trainingId'
      fullPath: '/formations/$trainingId/'
      preLoaderRoute: typeof InstructorFormationsTrainingIdIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/formations/$trainingId/contenu': {
      id: '/_instructor/formations/$trainingId/contenu'
      path: '/formations/$trainingId/contenu'
      fullPath: '/formations/$trainingId/contenu'
      preLoaderRoute: typeof InstructorFormationsTrainingIdContenuRouteImport
      parentRoute: typeof InstructorRoute
    }
  }
}

interface InstructorRouteChildren {
  InstructorCommunauteRoute: typeof InstructorCommunauteRoute
  InstructorCorrectionsRoute: typeof InstructorCorrectionsRoute
  InstructorProfilRoute: typeof InstructorProfilRoute
  InstructorSessionsRoute: typeof InstructorSessionsRoute
  InstructorApprenantsStudentIdRoute: typeof InstructorApprenantsStudentIdRoute
  InstructorApprenantsIndexRoute: typeof InstructorApprenantsIndexRoute
  InstructorFormationsIndexRoute: typeof InstructorFormationsIndexRoute
  InstructorFormationsTrainingIdContenuRoute: typeof InstructorFormationsTrainingIdContenuRoute
  InstructorFormationsTrainingIdIndexRoute: typeof InstructorFormationsTrainingIdIndexRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorCommunauteRoute: InstructorCommunauteRoute,
  InstructorCorrectionsRoute: InstructorCorrectionsRoute,
  InstructorProfilRoute: InstructorProfilRoute,
  InstructorSessionsRoute: InstructorSessionsRoute,
  InstructorApprenantsStudentIdRoute: InstructorApprenantsStudentIdRoute,
  InstructorApprenantsIndexRoute: InstructorApprenantsIndexRoute,
  InstructorFormationsIndexRoute: InstructorFormationsIndexRoute,
  InstructorFormationsTrainingIdContenuRoute:
    InstructorFormationsTrainingIdContenuRoute,
  InstructorFormationsTrainingIdIndexRoute:
    InstructorFormationsTrainingIdIndexRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstructorRoute: InstructorRouteWithChildren,
  InscriptionRoute: InscriptionRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  ReinitialisationRoute: ReinitialisationRoute,
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
