/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as InstructorRouteImport } from './routes/_instructor'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as ReinitialisationRouteImport } from './routes/reinitialisation'
import { Route as AuthInviteRouteImport } from './routes/_auth/invite'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as InstructorCommunauteRouteImport } from './routes/_instructor.communaute'
import { Route as InstructorDashboardRouteImport } from './routes/_instructor/dashboard'
import { Route as InstructorProfilRouteImport } from './routes/_instructor/profil'
import { Route as InstructorCorrectionsIndexRouteImport } from './routes/_instructor/corrections/index'
import { Route as InstructorSessionsSessionsRouteImport } from './routes/_instructor/sessions/sessions'
import { Route as InstructorStudentsIndexRouteImport } from './routes/_instructor/students/index'
import { Route as InstructorStudentsStudentIdRouteImport } from './routes/_instructor/students/$studentId'
import { Route as InstructorTrainingsIndexRouteImport } from './routes/_instructor/trainings/index'
import { Route as InstructorTrainingsTrainingIdIndexRouteImport } from './routes/_instructor/trainings/$trainingId/index'
import { Route as InstructorTrainingsTrainingIdContenuRouteImport } from './routes/_instructor/trainings/$trainingId/contenu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/_instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialisationRoute = ReinitialisationRouteImport.update({
  id: '/reinitialisation',
  path: '/reinitialisation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const InstructorCommunauteRoute = InstructorCommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorProfilRoute = InstructorProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorCorrectionsIndexRoute =
  InstructorCorrectionsIndexRouteImport.update({
    id: '/corrections/',
    path: '/corrections/',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorSessionsSessionsRoute =
  InstructorSessionsSessionsRouteImport.update({
    id: '/sessions/sessions',
    path: '/sessions/sessions',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorStudentsIndexRoute = InstructorStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorStudentsStudentIdRoute =
  InstructorStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorTrainingsIndexRoute =
  InstructorTrainingsIndexRouteImport.update({
    id: '/trainings/',
    path: '/trainings/',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorTrainingsTrainingIdIndexRoute =
  InstructorTrainingsTrainingIdIndexRouteImport.update({
    id: '/trainings/$trainingId/',
    path: '/trainings/$trainingId/',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorTrainingsTrainingIdContenuRoute =
  InstructorTrainingsTrainingIdContenuRouteImport.update({
    id: '/trainings/$trainingId/contenu',
    path: '/trainings/$trainingId/contenu',
    getParentRoute: () => InstructorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/invite': typeof AuthInviteRoute
  '/login': typeof AuthLoginRoute
  '/communaute': typeof InstructorCommunauteRoute
  '/dashboard': typeof InstructorDashboardRoute
  '/profil': typeof InstructorProfilRoute
  '/sessions/sessions': typeof InstructorSessionsSessionsRoute
  '/students/$studentId': typeof InstructorStudentsStudentIdRoute
  '/corrections/': typeof InstructorCorrectionsIndexRoute
  '/students/': typeof InstructorStudentsIndexRoute
  '/trainings/': typeof InstructorTrainingsIndexRoute
  '/trainings/$trainingId/contenu': typeof InstructorTrainingsTrainingIdContenuRoute
  '/trainings/$trainingId/': typeof InstructorTrainingsTrainingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/invite': typeof AuthInviteRoute
  '/login': typeof AuthLoginRoute
  '/communaute': typeof InstructorCommunauteRoute
  '/dashboard': typeof InstructorDashboardRoute
  '/profil': typeof InstructorProfilRoute
  '/sessions/sessions': typeof InstructorSessionsSessionsRoute
  '/students/$studentId': typeof InstructorStudentsStudentIdRoute
  '/corrections': typeof InstructorCorrectionsIndexRoute
  '/students': typeof InstructorStudentsIndexRoute
  '/trainings': typeof InstructorTrainingsIndexRoute
  '/trainings/$trainingId/contenu': typeof InstructorTrainingsTrainingIdContenuRoute
  '/trainings/$trainingId': typeof InstructorTrainingsTrainingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_instructor': typeof InstructorRouteWithChildren
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/_auth/invite': typeof AuthInviteRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_instructor/communaute': typeof InstructorCommunauteRoute
  '/_instructor/dashboard': typeof InstructorDashboardRoute
  '/_instructor/profil': typeof InstructorProfilRoute
  '/_instructor/sessions/sessions': typeof InstructorSessionsSessionsRoute
  '/_instructor/students/$studentId': typeof InstructorStudentsStudentIdRoute
  '/_instructor/corrections/': typeof InstructorCorrectionsIndexRoute
  '/_instructor/students/': typeof InstructorStudentsIndexRoute
  '/_instructor/trainings/': typeof InstructorTrainingsIndexRoute
  '/_instructor/trainings/$trainingId/contenu': typeof InstructorTrainingsTrainingIdContenuRoute
  '/_instructor/trainings/$trainingId/': typeof InstructorTrainingsTrainingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/reinitialisation'
    | '/invite'
    | '/login'
    | '/communaute'
    | '/dashboard'
    | '/profil'
    | '/sessions/sessions'
    | '/students/$studentId'
    | '/corrections/'
    | '/students/'
    | '/trainings/'
    | '/trainings/$trainingId/contenu'
    | '/trainings/$trainingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/reinitialisation'
    | '/invite'
    | '/login'
    | '/communaute'
    | '/dashboard'
    | '/profil'
    | '/sessions/sessions'
    | '/students/$studentId'
    | '/corrections'
    | '/students'
    | '/trainings'
    | '/trainings/$trainingId/contenu'
    | '/trainings/$trainingId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_instructor'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/reinitialisation'
    | '/_auth/invite'
    | '/_auth/login'
    | '/_instructor/communaute'
    | '/_instructor/dashboard'
    | '/_instructor/profil'
    | '/_instructor/sessions/sessions'
    | '/_instructor/students/$studentId'
    | '/_instructor/corrections/'
    | '/_instructor/students/'
    | '/_instructor/trainings/'
    | '/_instructor/trainings/$trainingId/contenu'
    | '/_instructor/trainings/$trainingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
  InscriptionRoute: typeof InscriptionRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  ReinitialisationRoute: typeof ReinitialisationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_instructor': {
      id: '/_instructor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialisation': {
      id: '/reinitialisation'
      path: '/reinitialisation'
      fullPath: '/reinitialisation'
      preLoaderRoute: typeof ReinitialisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/invite': {
      id: '/_auth/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_instructor/communaute': {
      id: '/_instructor/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof InstructorCommunauteRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/dashboard': {
      id: '/_instructor/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/profil': {
      id: '/_instructor/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof InstructorProfilRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/corrections/': {
      id: '/_instructor/corrections/'
      path: '/corrections'
      fullPath: '/corrections/'
      preLoaderRoute: typeof InstructorCorrectionsIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/sessions/sessions': {
      id: '/_instructor/sessions/sessions'
      path: '/sessions/sessions'
      fullPath: '/sessions/sessions'
      preLoaderRoute: typeof InstructorSessionsSessionsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/students/': {
      id: '/_instructor/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof InstructorStudentsIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/students/$studentId': {
      id: '/_instructor/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof InstructorStudentsStudentIdRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/trainings/': {
      id: '/_instructor/trainings/'
      path: '/trainings'
      fullPath: '/trainings/'
      preLoaderRoute: typeof InstructorTrainingsIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/trainings/$trainingId/': {
      id: '/_instructor/trainings/$trainingId/'
      path: '/trainings/$trainingId'
      fullPath: '/trainings/$trainingId/'
      preLoaderRoute: typeof InstructorTrainingsTrainingIdIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/trainings/$trainingId/contenu': {
      id: '/_instructor/trainings/$trainingId/contenu'
      path: '/trainings/$trainingId/contenu'
      fullPath: '/trainings/$trainingId/contenu'
      preLoaderRoute: typeof InstructorTrainingsTrainingIdContenuRouteImport
      parentRoute: typeof InstructorRoute
    }
  }
}

interface AuthRouteChildren {
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface InstructorRouteChildren {
  InstructorCommunauteRoute: typeof InstructorCommunauteRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorProfilRoute: typeof InstructorProfilRoute
  InstructorSessionsSessionsRoute: typeof InstructorSessionsSessionsRoute
  InstructorStudentsStudentIdRoute: typeof InstructorStudentsStudentIdRoute
  InstructorCorrectionsIndexRoute: typeof InstructorCorrectionsIndexRoute
  InstructorStudentsIndexRoute: typeof InstructorStudentsIndexRoute
  InstructorTrainingsIndexRoute: typeof InstructorTrainingsIndexRoute
  InstructorTrainingsTrainingIdContenuRoute: typeof InstructorTrainingsTrainingIdContenuRoute
  InstructorTrainingsTrainingIdIndexRoute: typeof InstructorTrainingsTrainingIdIndexRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorCommunauteRoute: InstructorCommunauteRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorProfilRoute: InstructorProfilRoute,
  InstructorSessionsSessionsRoute: InstructorSessionsSessionsRoute,
  InstructorStudentsStudentIdRoute: InstructorStudentsStudentIdRoute,
  InstructorCorrectionsIndexRoute: InstructorCorrectionsIndexRoute,
  InstructorStudentsIndexRoute: InstructorStudentsIndexRoute,
  InstructorTrainingsIndexRoute: InstructorTrainingsIndexRoute,
  InstructorTrainingsTrainingIdContenuRoute:
    InstructorTrainingsTrainingIdContenuRoute,
  InstructorTrainingsTrainingIdIndexRoute:
    InstructorTrainingsTrainingIdIndexRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
  InscriptionRoute: InscriptionRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  ReinitialisationRoute: ReinitialisationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
